import os
from datetime import datetime


def generate_report(enriched, triage):
    """Turn an enriched alert + triage result into a Markdown report string."""

    alert = enriched["alert"]
    ip_data = enriched["enrichment"]["ip"]
    hash_data = enriched["enrichment"]["hash"]
    flags = enriched.get("risk_flags", [])

    # Build the MITRE table rows. Mark anything that failed validation.
    mitre_rows = ""
    for m in triage.get("mitre", []):
        status = "✅" if m.get("valid") else "⚠️ UNVERIFIED"
        name = m.get("official_name") or m.get("technique", "")
        mitre_rows += f"| {m.get('id','')} | {name} | {m.get('tactic','')} | {status} |\n"

    # Build the recommended-actions list.
    action_lines = ""
    for i, action in enumerate(triage.get("recommended_actions", []), start=1):
        action_lines += f"{i}. {action}\n"

    # Assemble the full report using an f-string template.
    report = f"""# Incident Report: {alert.get('alert_name','Unknown Alert')}

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}
**Alert ID:** {alert.get('alert_id','N/A')}

---

## 1. Executive Summary

{triage.get('summary','No summary available.')}

**Severity:** {triage.get('severity','unknown').upper()} — {triage.get('severity_reason','')}
**Triage Decision:** {triage.get('triage_decision','unknown')}
**Confidence:** {triage.get('confidence','unknown')}

---

## 2. Alert Details

| Field | Value |
|-------|-------|
| Timestamp | {alert.get('timestamp','N/A')} |
| Host | {alert.get('host','N/A')} |
| User | {alert.get('user','N/A')} |
| Source IP | {alert.get('src_ip','N/A')} |
| Destination IP | {alert.get('dest_ip','N/A')} |
| Process | {alert.get('process','N/A')} |

---

## 3. Enrichment Findings

**Destination IP ({ip_data.get('ip','N/A')})**
- Abuse score: {ip_data.get('abuse_score','unknown')}/100
- Country: {ip_data.get('country','unknown')}
- ISP: {ip_data.get('isp','unknown')}
- Tor exit node: {ip_data.get('is_tor','unknown')}

**File Hash ({hash_data.get('hash','N/A')})**
- Malicious detections: {hash_data.get('malicious','unknown')}
- Known name: {hash_data.get('meaningful_name','unknown')}

**Risk Flags:** {', '.join(flags) if flags else 'none'}

---

## 4. MITRE ATT&CK Mapping

| Technique ID | Name | Tactic | Status |
|--------------|------|--------|--------|
{mitre_rows}
---

## 5. Recommended Response

{action_lines}
---

*Report generated by AI SOC Analyst. MITRE techniques validated against the official ATT&CK dataset.*
"""
    return report


def save_report(report_text, alert_id):
    """Write the report to the reports/ folder as a .md file."""
    os.makedirs("reports", exist_ok=True)
    path = f"reports/incident_{alert_id}.md"
    with open(path, "w", encoding="utf-8") as f:
        f.write(report_text)
    return path